version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend-to-do-list
    tty: true
    stdin_open: true
    command: bash
    restart: always
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=backend
    depends_on:
      - database
      - backend
  backend:
    build: ./backend
    container_name: backend-to-do-list
    tty: true
    stdin_open: true
    command: bash
    restart: always
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: database
      PORT: '3001'
    depends_on:
      - database
  database:
    image: mysql
    container_name: to-do-list-database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
networks:
  default:
    name: network-to-do-list
